cassandra:
  nodes:
    - "node_ips"
    - "add node ips in list"
  keyspace: "benchmark"
  table: "employees"

benchmark:
  duration_seconds: 300
  requests_per_second : 10000
  warmup_seconds: 5
  concurrency: 100
  read_ratio: 0.8
  write_ratio: 0.2
  mode: "open-loop" 
  log_file: "result.json"
