hosts:
  - 155.98.38.146 
  - 155.98.38.130
keyspace: benchmark
table: benchmark_table
reads: 70
writes: 30
concurrency: 100
warmup_time: 10
duration: 60
loop_type: "open"  
max_concurrency: 1000
failure_threshold: 0.05
