cassandra:
  nodes:
    - "155.98.38.148"
    - "155.98.38.155"
    - "155.98.38.236"
  keyspace: "bench"
  table: "employees"

benchmark:
  duration_seconds: 20
  requests_per_second : 1000
  warmup_seconds: 5
  concurrency: 10
  read_ratio: 0.7
  write_ratio: 0.3
  mode: "open-loop" 
  log_file: "result.json"
  
