cassandra:
  nodes:
    - "155.98.38.235"
    - "155.98.38.236"
  keyspace: "bench"
  table: "employees"

benchmark:
  duration_seconds: 60
  warmup_seconds: 10
  concurrency: 10
  read_ratio: 0.5
  write_ratio: 0.5
  mode: "closed-loop"
  log_file: "result.json"
